export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'CUSTOMER_NOT_FOUND'
  | 'DUPLICATE_CUSTOMER'
  | 'INVALID_MOBILE'
  | 'INVALID_VEHICLE_NUMBER'
  | 'INVALID_LITRES'
  | 'OTP_INVALID'
  | 'OTP_EXPIRED'
  | 'OTP_ATTEMPTS_EXCEEDED'
  | 'OTP_RESEND_TOO_SOON'
  | 'NOT_ELIGIBLE_FOR_REDEMPTION'
  | 'INSUFFICIENT_CASHBACK'
  | 'DUPLICATE_REDEMPTION'
  | 'REDEMPTION_NOT_FOUND'
  | 'INVALID_REDEMPTION_STATE'
  | 'WHATSAPP_FAILED'
  | 'READER_FAILED'
  | 'READER_TIMEOUT'
  | 'RATE_LIMITED'
  | 'INTERNAL_ERROR';

const STATUS_BY_CODE: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  CUSTOMER_NOT_FOUND: 404,
  DUPLICATE_CUSTOMER: 409,
  INVALID_MOBILE: 400,
  INVALID_VEHICLE_NUMBER: 400,
  INVALID_LITRES: 400,
  OTP_INVALID: 400,
  OTP_EXPIRED: 400,
  OTP_ATTEMPTS_EXCEEDED: 429,
  OTP_RESEND_TOO_SOON: 429,
  NOT_ELIGIBLE_FOR_REDEMPTION: 422,
  INSUFFICIENT_CASHBACK: 422,
  DUPLICATE_REDEMPTION: 409,
  REDEMPTION_NOT_FOUND: 404,
  INVALID_REDEMPTION_STATE: 409,
  WHATSAPP_FAILED: 502,
  READER_FAILED: 502,
  READER_TIMEOUT: 504,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};

export class AppError extends Error {
  code: ErrorCode;
  status: number;
  details?: unknown;

  constructor(code: ErrorCode, message: string, details?: unknown) {
    super(message);
    this.name = 'AppError';
    this.code = code;
    this.status = STATUS_BY_CODE[code];
    this.details = details;
  }
}
